---
- project:
    check:
      jobs:
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-linters
    post:
      jobs:
        - stx-containers-upload-git-mirror

- job:
    name: stx-containers-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/containers to
      github.com/starlingx/containers
    vars:
      git_mirror_repository: starlingx/containers
    secrets:
      - name: git_mirror_credentials
        secret: stx-containers-github-secret3
        pass-to-parent: true

- secret:
    name: stx-containers-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - aZ1D5MtDB3YtThPlTrkMnP3H4GzS36oI8FM6o9ytmtScu1IBkcdPVEc0dxEiDB8kv7Csf
          oeqK381lWmmf/7dczkeB6utN6IJes8FHI+0qAHdwBAJZGMW8wyaP5N7wmK15Lz1Qsvju7
          WXpSDKRcMHE8JqNCNmZDJCNHhsRmFh7KyYAlhb1t6rS1EE7cFXm11DT+X4TSTau1ZCSkF
          n7p0IlfLZ5mgH+Om3PsDx7xfC80ntTTXbzPCsrzBMKKc5RzvEMG2BWuQnvktvY4prLgFl
          ptgRHOZZ9HFqYd+OPjhcGoAAzx6UPLpBSAtjQ7YRs2x2ghdwrDQQOpOkQs5VtAMiHe1LJ
          f8wLR5LtWKFf4+asnhNY96oSkfTpnButVKjPC5a5HskBkXdrghNKYHSnkPip6v4xhBfIP
          uYgGSn/TafDBCOVadtI1DKNlwiq2zg9ategVI7TomvR13VDN5kijODR+Ln+5fHtQybQdm
          JFhEBzgxb0HABvRwVAJg0QWboDCWpeJaNkL3iUo2chcQ1HQmoTcNADqi/XRJFr+ZeOJSV
          SIwYiWu9heoHo+JMP8QM/TZQOS/jmNkpqWHL0pIAg8Z5qa6X3Z4HowCahWeBYLGwkvIa/
          xB3il5VUdCcLADytRQZumkQvInZhcM9vONJGVKECWcvt8KebxkSUKwACwI2Xl0=
        - W08m9mmZCyUMNAHKjeKqPjzOLjvlYbb/+/H1SP1dh5vWpdmRa7wjNEjogs1R65NLdX/+d
          jTTFFFWLKa818ROpvxSlK1bc9wOgQaBSX0CuWNDq46/lz2cV3i9XACSsXX0Ic+qTr7D2L
          IkBh55dSHXY81TmlXazvxBsluDhjRnmBphQcBymFuBOT2aq3i86iNVwEsp07S3o6gYBrg
          pNfEJ2mkOhf6fPLzp0GNAxEE6k6YuKpfltDG+PogAe6DQOHN6SHqpNMXJFIXwLdFdlMNM
          DgPCmP7gRUwnvJQSE2phzi2uoj+EB0Y/swX5mBLahysuPFSFEzOWjvTcBUFZ34vYs4hGr
          TAfBY50AtUhKOLJgnpCoA2266kI9sXuhD/7Ofv7VjY4JlMzhLeiiwJ0hcUvLbhcr2FK8u
          UOtTFDGRSGl1NhSTBRjobN40ySayy3M9SrdPn27KRUFRAwD7IZYfXIBFfrRKJiXBJB4+l
          T6dnN9QasPi4tZ6ylbV/lOJgGWh8H+8zb3g4bv5LSJWAarPV8RVZssSMgvpiWlHtFieGn
          Wxfa7FdFhnj9SX7BGgDHXl4Qf/+pv4nj0RFskkCKaWMv1m6Pw53ekmB7TIjndr04vyqHa
          CAWYRZMJHW5kDNXD1/0ghH5WMj9mIRrMUCcVNmRf8V7IbUiYYYys+2wb4ZPrAc=
        - hlHU13VhKJC2n6Qs44924eADuNZKlCRS9baO3qfEyRDIyljnO1jpJg1XYHdNvLa10ChVW
          9t+CgUofD9g6qlss8EPHaVqmqOAx/c3A8BE0C6VCblaXS0PbHBb1dGwWqUZuW5rUPS1oR
          1KBo5zURZWMO8oqa1iNdwA5iwywJIIgVtz2Z6yAy/uY6Oa9qR7rqjwAO8tPKVCyYOmDQx
          Qj9M98cEpIMhN+Xw0NAT4TceUlDCj7cRuhKSNyT3fKFlMUKrhsh0JN3WLs7GpVaBmg0py
          cZKms+LKaSWGa/uH/fxJi+X96y/eeOADTid8uRl32J3vTuzVirJkJHeQCsIkbsX2CDptu
          N5si7kK0H58ZSnXvAi+3rvZ0c3twFd6POcVnFV94TMbweaGjysRlx46D99mpu3rgi8acp
          ZJileAHmbvvdWLOhXowMJneL5TtlA2uPtHIBtoFFk/EypOvNTTiSeXadacFWVHwuKL5pQ
          lz4GIPqWiFt6KDKAdHeCmj5OchRAiahe+/qqUQtzf67dS5Eo9WCRGQhIMtSUjIZa5Y+s3
          +CHsLXczqluFA3weGuSx+etes3dVEidOgO7NDDD/yL/2Mg805iuvqNM5CFrzI+c4EXipt
          t73wdtPt4PFvOsQ5PWBDx/lLh5XWPC0Z5CfLJ4n9guVjnDM9KQdRZxVmSeegZY=
        - katpIbhlI+/diffR0LpYmfS2dOummFLYYLr086pnt3WAXuzQPFmopkgvmRlEcdn20pLih
          czZDifyp0iOfZsJbFiqMCn8qNQK/bI7peGxkxU+toSskcm6hfcIGD/irjshEpdlErDzXD
          dRgPYVxImULmW7q4I9Cu/3aPJJWHZrwmSUjm4JRqErvjyozqROQLZHDmCqXnXjAUuVW35
          /OW3ImGKcULtOuGrKkyg+kXFsmX/ecqK/6uakPZOK6QMuoVfkVFMuidGm4TdQOU1hiNc8
          pEAl2kAxQ82PLbsy0ZuWPSqvYmVLlBGJ3jM5oAz/m14zg+shcTrT7j4LaxFHCwbEv1+Fo
          u2D5znnPW6hvqRCospX/+j4yaYz7ArKK3h6ioSZunAKkxZKAYVbZuSRGdN3xCdesgnNv0
          lAWDTB6MxtcOO6Tj6+8kcDLV42ReyYR5accmzMidPp4TYDUfTsG5ArYIokhU2SKf/HDs3
          JM3txVsvDCx4WAy5A74GnFiRxNi0ZbdOTS28Gm+pgmvbAdI4Y5/5dxE8Pu4RyKgq3sHFG
          4MrNl5IMYVvloSdDZDz63kCpkZRMZteS+MUuFHy2gwCiCMUTUhau/jc62qChBfsXrcZ0z
          lGD1WYYVZMX6Ieo/rq9NW6dGGfp3ECJ+O1NyDmQRZYN0iFAc++6JH7Ma9SWvFk=
        - fcmScpSYG9dfZVPYySVovOf/exJfwalt9Tww5OVfnN6Uc0SEBb4YF8iPDUSvUz7Tkux1w
          P2HdGh/Cay4mgRhiHB4AUciv9P0nhMMFH9vRfb3DujD88lJyITDOgJvmGzgowegbME/bA
          eMuclUN7eqWmi/c3z43Q4x1hT+O6SFcIxSHUpwALuJlcq7bPUKZUYj/QD1+MWc0cVpJAZ
          M+xXoWhQ7i4bCvXOA8uhZ/1bsQxqgWuMgtTfOXzHqapJ/sPHvoYlIUC+41m+75rqjicQ5
          oWwOBL9sbup0IcO58tUWkh0piUuDHZmDXVPrye1B4EQtOH26KjtJYjUIBb9hn+nA97Ej9
          rDf0urMzYVv/eWxrHeMTq1ann5WXCV6fR1pMUwzFX0/Z+gwhvtPqs8I3LJeeMiBl/LECN
          MixJuKNXg7P9pAfjo2gVXdcApaamrVR0aKXoYHLWErlzHljLplLu/XYdnLnnBfE1gs7ly
          xku4TjPaUe3n8BukgJ03fgzxe8rLCwsNY1fiVszFdz1NIkE+vcnuLjfC03BLQWZTkOhjB
          mtw7f+PVpDH+yirbxYujMn++7HPFWzv7IyPpH3jJDqXm0eLz/o+RheB/3S5hBJsNVRcrS
          mmu0FDq+oDdMUElzFk2zYvLqU8sT8F+sYXE1Z/s2JsROvLQntBEIZwOINfjte4=
        - MyulRZmR/tUoZP5C5Kul0kEDuwKGKZPZtO4FdUsv+h1y/+grOpBrGnrM29VkhYZ0Us9S0
          0n8PhrdsaElgQ3CXBE47Ox7Xy0ur1i7unWFp4eH/1gus5E+ANhvAWoZbHQAgCn4UrUmFZ
          hXnfdgSC6fOav08a8xTFWO/i0yAuFE/wX6bVWPg6nIWDg1qvQkqYI55rbGG81WvD5PI/S
          oXqmgOr4OU8VgpQ/J7Yvy8Cm5iMsY8P1K8G1aHhfZalMPqBAiFJfXVy6C10hAq4vyhcy6
          24KSrU3yz9UgH9S/q+HZV7mKr/eHwLa+IoXOyBqW5odONFkORSdEd9bWgdtFT+ObqgjzZ
          zk/tgFo2uL7jcHFGYuK0zn6fgG3SW43HO8yKvwmNmjtG65bJPiYJiT/w3t2kzFapqM0ys
          Pp1agbZJHw0NSwjWivou7FVDFjb7He2dA8KHD3lRcaglk1fNZoJZ1rc/WvTVIpxfTXf5/
          affSVEIM4nUEVRTOAG82lePo/lFdYc0vdEF0jpMpl17CcwCB/XJ8QvzBA79Q0IlIesiYf
          RhK4saG9dbO706wEqUY7m35FeaN8gQVJx+UyijuQ9R+w4qJWgeAL9Aj9CA8+UUjxdloOu
          w9JriWatFvzR0qlVqapkJLvKr9v8abTf6j84LdY/eYbMWbrtBEFnIqUgHPdgJ4=
        - roZSp9TmXzyfupNvz9aVKvEotb/2L4ha8g8jlk7Rv3Dx+pJlgil92QVEqLjmZUDmghDr3
          fJBu3nyTPweKjK61w6etRQsp6Ic//SfTJKQNrtScNIV74TbIM3jEX6Wr88n7CPGNqBfyr
          vHCPHD1he0C7Ohjr3yCgpa9DOtF70PlypEtJHCQBNkw3+cAG2F8V41+OQsc91nghNsKy5
          hateFQf93hQOCEhAW9ZOehm+YJhiykSYabVVubkHoJJlYzNTSjMm04ld3HBN/8aUP5bYy
          0QKMVpr6snkcErENBXZKP5B1i/1Cd3qW49xL+Qw83bJDL7GvnHBjtRZbjuvg9We5oMUqC
          TaBw6izzXe06+0FYjX12PVGsOWg0wJ+lWiu+M73XAtnwxRXT+TnD9J96ssQll46ssFnpj
          J9l8BMm+6T5Vgl1XfclrE1ZJwBMR8IVVTed173jeQiZ/Ofg8Eb1fAm6t8J6GKN7d2mThd
          jmXGa5CrXsVPfHXFuS2rUBr7f1oHM6FHFBwdfH6q/yT020FHGWHegStQmhq7+O/T9vOem
          xNrW2k5E9Dh3A848godcw72suC2XwVnwL+DVrdMuKV+oG+zkDzbDA+afCHdW1v0/RilTI
          zRYWMz/iclEejtqDZ5jTW6xwFn4smLlTOq9OEpaH7/CtaDkfDwqXbKC69ZJs18=
