#!/bin/bash

set -x

pull_source() {
  if [ "$1" = "" ] ; then
    exit 1
  fi
  cp -r $1 ${PKG_BUILD_ROOT}/
}

############################################
### WORKAROUND until build tools support ###
############################################
STX_MIRROR=$(realpath "/import/mirrors/starlingx")
######################
### END WORKAROUND ###
######################
STX_BASE=$(realpath ${MY_REPO}/stx)
STX_SOURCES=$(realpath ${STX_BASE}/containers/registry-token-server)

SRC=$(realpath ${STX_BASE}/containers/registry-token-server/src)
EXTRA_FILE_SRC1=$(realpath ${STX_SOURCES}/centos/files/token_server.conf)
SUBMODULE_SRC1=$(realpath ${STX_MIRROR}/downloads/Sirupsen-logrus-3d4380f53a34dcdc95f0c1db702615992b38d9a4.tar.gz)
SUBMODULE_SRC2=$(realpath ${STX_MIRROR}/downloads/docker-distribution-v2.7.1.tar.gz)
SUBMODULE_SRC3=$(realpath ${STX_MIRROR}/downloads/docker-libtrust-fa567046d9b14f6aa788882a950d69651d230b21.tar.gz)
SUBMODULE_SRC4=$(realpath ${STX_MIRROR}/downloads/gophercloud-gophercloud-aa00757ee3ab58e53520b6cb910ca0543116400a.tar.gz)
SUBMODULE_SRC5=$(realpath ${STX_MIRROR}/downloads/gorilla-mux-599cba5e7b6137d46ddf58fb1765f5d928e69604.tar.gz)


PKG_BUILD_NAME=$1
PKG_BUILD_ROOT=$(realpath `pwd`/${PKG_BUILD_NAME})
mkdir ${PKG_BUILD_NAME}
pushd ${PKG_BUILD_NAME}

# Get main package sources
cp -r ${SRC}/* ${PKG_BUILD_ROOT}/
# Get extra files
pull_source ${EXTRA_FILE_SRC1}

# Get submodules
pull_source ${SUBMODULE_SRC1} && \
pull_source ${SUBMODULE_SRC2} && \
pull_source ${SUBMODULE_SRC3} && \
pull_source ${SUBMODULE_SRC4} && \
pull_source ${SUBMODULE_SRC5}
rc=$(echo $?)
if [ "${rc}" != "0" ] ; then
  exit ${rc}
fi

# Workaround go install issue
# case-insensitive import collision: "github.com/sirupsen/logrus" and "github.com/Sirupsen/logrus"
# Before implementing the fix by transforming to lowercase Sirupsen, this needs to be tested CentOS side.
sed -i 's@github.com/Sirupsen/logrus@github.com/sirupsen/logrus@g' main.go
